menu:
    博文: /
    归档: /archives/
    生活: /categories/live/
    读书: /categories/read/
    关于: /about/

widgets:
- category
- tag
- tagcloud
- archive

# count
show_count: true
favicon: http://image.xiaoed.com/blog/image/xiaoed-blog.png-128.png
logo: http://image.xiaoed.com/blog/image/xiaoed-blog.png-128.png
style: http://image.xiaoed.com/blog/css/bubuzou.css
# style: css/bubuzou.css

# Comment
#changyan: bubuzou
leancloud:
    appid: CSoYDTggxz9zEqaPGhtj2Fbp-gzGzoHsz # 填写您的appid
    appkey: FDj4DHDrK0MxN5qsU3G2pLwa # 填写您的appkey
    comment: true # 是否开启评论系统
    counter: true # 是否开启文章统计


# Analytics
# google-analytics:
# ga: UA-65933410-1

# Copyright Infomation
startyear: 2019

